services:
  backend:
    image: lastercho/flatmoneyback:1.1.0
    container_name: flatmoneyback
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Пренасочете порта на приложението
    environment:
      - DB_USER=laster
      - DB_PASSWORD=SamoZaproba321
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=flatmoney
      - JWT_SECRET=sadfassd-sadfasdfas-asdfascvhvbnghj-r5trcvxc-wefsdxxzcvzxc-sewerdfgsdfg
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: flatmoneypostgres
    environment:
      POSTGRES_USER: laster
      POSTGRES_PASSWORD: SamoZaproba321
      POSTGRES_DB: flatmoney
    ports:
      - "5432:5432" # Пренасочете порта на PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: